### ISSUE TITLE
Error in inherits(x, "xts") : could not find function "C1"

### ISSUE THREAD

**Issue by msmith01** [timtrice/backtesting-strategies#14]
Hello,

I am currently on [section 8.6](https://timtrice.github.io/backtesting-strategies/stop-loss.html#apply-strategy-1) and I am getting an error.

> Error in inherits(x, "xts") : could not find function "C1"

I have checked my code and I have followed the tutorial exactly. I have two functions called basic_symbols and checkBlotterUpdate.

The indicator C1 is located in the add.indicator

```
add.indicator(strategy = strategy.st,
              name = "SMA",
              arguments = list(x = quote(Cl(mktdata)), 
                               n = 10),
              label = "nFast")

add.indicator(strategy = strategy.st, 
              name = "SMA", 
              arguments = list(x = quote(Cl(mktdata)), 
                               n = 30), 
              label = "nSlow")



Best

**Comment by timtrice** [comment]
The function `Cl` (lower-case L), not C1.
